project_name: "my_app"
main_file: "main.py"
output_name: "my_app.exe"

project_libs: []
include_packages: []
include_data_dirs: []

icon_file: null

windows_metadata:
  product_name: "My Application"
  file_description: "My Python Application"
  product_version: "1.0.0.0"
  file_version: "1.0.0.0"
  copyright: "My Company"
  company_name: "My Company"

build_libs:
  - "nuitka"
  - "ordered-set"

nuitka_plugins:
  - "upx"
  - "no-qt"
  - "tk-inter"

nuitka_extra_args:
  - "--lto=no"
  - "--show-scons"
  - "--jobs=1"

cleanup_items:
  - "build"
  - "dist"
