# PyCompiler Configuration
# 
# This file configures your Python to executable conversion.
# Only 3 fields are required - everything else is optional!

# ==========================================
# REQUIRED - Fill these 3 fields
# ==========================================
project_name: "my_app"        # Your app name
main_file: "main.py"          # Your main Python file
output_name: "my_app.exe"     # Output executable name

# ==========================================
# OPTIONAL - Add if needed
# ==========================================

# Your Python dependencies
project_libs: []
# project_libs:
#   - "requests"
#   - "pandas"

# Python packages to include
include_packages: []
# include_packages:
#   - "src"

# Windows executable icon
icon_file: null
# icon_file: "icon.ico"

# ==========================================
# WINDOWS METADATA - Customize .exe properties
# ==========================================
windows_metadata:
  product_name: "My Application"
  file_description: "My Python Application"
  product_version: "1.0.0.0"
  file_version: "1.0.0.0"
  copyright: "My Company"
  company_name: "My Company"

# ==========================================
# ADVANCED - Don't change unless needed
# ==========================================

# Build dependencies (auto-installed)
build_libs:
  - "nuitka"
  - "ordered-set"

# Data directories to include
include_data_dirs: []
# include_data_dirs:
#   - "assets=assets"

# Nuitka plugins
nuitka_plugins:
  - "upx"           # Compress size
  - "no-qt"         # Exclude Qt
  - "tk-inter"      # Include Tkinter

# Additional Nuitka arguments
nuitka_extra_args:
  - "--lto=no"
  - "--show-scons"
  - "--jobs=1"

# Additional cleanup files
cleanup_items: []
# cleanup_items:
#   - "build"